name: eloquent-projects
services:
  app:
    image: ghcr.io/whilesmartphp/laravel-dev:package-8.4
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - APP_ENV=testing

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
